### ISSUE TITLE
Potential Incorrect Information in Solana CAIP-10

### ISSUE THREAD

**Issue by RyanTimesTen** [ChainAgnostic/namespaces#60]
Hello 👋 

I'm bringing up what I believe is a discrepancy between [Solana CAIP-2](https://github.com/ChainAgnostic/namespaces/blob/main/solana/caip2.md) and [Solana CAIP-10](https://github.com/ChainAgnostic/namespaces/blob/main/solana/caip10.md). Specifically, the Chain IDs do not match up, and I believe CAIP-2 has the correct values and CAIP-10 does not.

According to the [Chain ID Resolution Method](https://github.com/ChainAgnostic/namespaces/blob/main/solana/caip2.md#resolution-method) in CAIP-2:
> To resolve a blockchain reference for the Solana namespace, make a JSON-RPC request to the [RPC Endpoints](https://docs.solana.com/cluster/rpc-endpoints) of a blockchain node with method getGenesisHash, for example:
// Request
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "getGenesisHash"
}
// Response
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": "5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d"
}

And in fact, executing this resolution method on the Solana Mainnet RPC endpoint:
```
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "getGenesisHash"
}
'
```

yields this result
```
{"jsonrpc":"2.0","result":"5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d","id":1}
```

So the Chain ID for Solana Mainnet is `5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d`, as stated in CAIP-2, and the Chain ID stated in CAIP-10 is wrong. This is reproducible with the stated Chain ID for Solana Devnet.

Please let me know if I'm missing something, otherwise I'd be happy to open a Pull Request to correct this. Thanks!

**Comment by bumblefudge** [comment]
Whoooops you are correct ser.  I think the CAIP-10 examples were using the [blockHash of block 0](https://explorer.solana.com/block/0) rather than the genesis hash proper, i.e.

```bash
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0","id":1,
    "method":"getBlock",
    "params": [
      0,
      {
        "encoding": "json",
        "maxSupportedTransactionVersion":0,
        "transactionDetails":"full",
        "rewards":false
      }
    ]
  }
'
```

Feel free to open a PR if you have time and want the commit history! Otherwise I'll get to it next week.

**Comment by RyanTimesTen** [comment]
cool, check the pr when you have time ☝️

**Comment by lguild-plaid** [comment]
similar fix for CAIP-19 ☝️
