### ISSUE TITLE
Incorrect Example in Solana CAIP-19

### ISSUE THREAD

**Issue by Sneh1999** [ChainAgnostic/namespaces#73]
Hello 👋

I believe one of the examples mentioned in Solana [CAIP-19](https://github.com/ChainAgnostic/namespaces/blob/main/solana/caip19.md) is incorrect 

Instead of 

```
# One Solana Mainnet NFT：Pesky Penguins #398
solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp/token:Fz6LxeUg5qjesYX3BdmtTwyyzBtMxk644XiTqU5W3w9w
```

the example should be 

```
# One Solana Mainnet NFT：Pesky Penguins #398
solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp/nft:Fz6LxeUg5qjesYX3BdmtTwyyzBtMxk644XiTqU5W3w9w
```

**Comment by bumblefudge** [comment]
you're right, if those addresses actually map to those examples! would you care to open the PR yourself to get the git-credit? if not i'll just patch it myself

**Comment by Sneh1999** [comment]
Done! https://github.com/ChainAgnostic/namespaces/pull/80
